DROP TABLE PRODUCTO;
DROP TABLE USUARIO;
DROP TABLE PEDIDO;
DROP TABLE DETALLE_PEDIDO;
DROP TABLE BOLETA;

CREATE  TABLE USUARIO(
    RUT_USUARIO INT NOT NULL,
    ROL INT CHECK(ROL BETWEEN 0 AND 3),
    NOMBRE_ROL VARCHAR2(100),
    NOMBRE_USUARIO VARCHAR2(100),
    PASWORD INT NOT NULL
    );

CREATE TABLE PRODUCTO(
    ID_PRODUCTO INT NOT NULL,
    NOMBRE VARCHAR2(200) CHECK(NOMBRE IN ('COMPLETO','BEBIDA','ITALIANO','ESPECIAL','JUGO')),
    PRECIO INT CHECK(PRECIO>=0),
    STOCK INT CHECK(STOCK>=0)
    );

CREATE TABLE PEDIDO(
    ID_PEDIDO INT NOT NULL,
    RUT_USUARIO INT NOT NULL,
    PRODUCTOS VARCHAR2(100),
    CANT_PRO INT CHECK(CANT_PRO >= 0),
    TOTAL INT NOT NULL,
    NRO_MESA INT NOT NULL,
    ESTADO INT CHECK(ESTADO BETWEEN 0 AND 1)
    );
    
CREATE TABLE DETALLE_PEDIDO(
    ID_DETALLE INT NOT NULL,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO INT NOT NULL
);

CREATE TABLE BOLETA(
    ID_PEDIDO INT NOT NULL,
    ID_BOLETA INT NOT NULL,
    PRODUCTOS VARCHAR2(100),
    RUT_USUARIO INT NOT NULL,
    TOTAL_F INT NOT NULL
    );
    
ALTER TABLE BOLETA ADD CONSTRAINT PK_BOLETA PRIMARY KEY(ID_BOLETA);
ALTER TABLE PEDIDO ADD CONSTRAINT PK_PEDIDO PRIMARY KEY(ID_PEDIDO);
ALTER TABLE DETALLE_PEDIDO ADD CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY(ID_DETALLE);
ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY(ID_PRODUCTO);
ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY(RUT_USUARIO);

ALTER TABLE BOLETA ADD CONSTRAINT FK_BOLETA_USUARIO FOREIGN KEY (RUT_USUARIO) REFERENCES USUARIO(RUT_USUARIO);
ALTER TABLE BOLETA ADD CONSTRAINT FK_BOLETA_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO);
ALTER TABLE DETALLE_PEDIDO ADD CONSTRAINT FK_DETALLE_PEDIDO_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO);
ALTER TABLE DETALLE_PEDIDO ADD CONSTRAINT FK_DETALLE_PEDIDO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO);
