DECLARE
    MENSAJE VARCHAR2(100);
    RESULTADO VARCHAR2(100);
BEGIN
    INSERTAR_ACCESORIOS(3, 'HOLA', 1, RESULTADO, MENSAJE);
    DBMS_OUTPUT.PUT_LINE(' - ' || MENSAJE);
END;

SET SERVEROUTPUT ON
