DROP TABLE NUM_TELEFONOS;
DROP TABLE SUBORDINADOS;
DROP TABLE ACCESORIOS;
DROP TABLE ALTO_MANDO;
DROP TABLE ARMAMENTO;
DROP TABLE ARSENAL;
DROP TABLE BASES;
DROP TABLE DIRECCION;
DROP TABLE EQUIPO;
DROP TABLE ESPECIALIDADES;
DROP TABLE ESPECIALIDAD;
DROP TABLE PERSONAL;
DROP TABLE RANGOS;
DROP TABLE TELEFONOS;

INSERT INTO NUM_TELEFONOS VALUES(2, 937);

INSERT INTO TELEFONOS_P VALUES(2, 20521, 2);


INSERT INTO PERSONAL VALUES (20521,'GUILLE','RAMOS',12, '12/03/2001',12, 1,1,1);
INSERT INTO RANGOS VALUES (1,'JEFE','EL BOSS');

INSERT INTO BASES VALUES (1,'TALCA',1);
INSERT INTO DIRECCION VALUES (1,'1','MAULE', 'LINARES', 'EL PEÑASCO', 880, 129);

INSERT INTO ESPECIALIDAD VALUES (4, 100, 'casa');

INSERT INTO ESPECIALIDAD VALUES (1, 100, 'SNIPER');
INSERT INTO ESPECIALIDADES VALUES (3,20521,3);

INSERT INTO ARMAMENTO VALUES(2, 'CUATCO', 1, 'CUATICO', 40, 300);

INSERT INTO EQUIPO VALUES(1, 'LPF', 1);

INSERT INTO ARSENAL VALUES(2,1,2);

INSERT INTO ACCESORIOS VALUES(1, 'LPF', 1);

select nombre_especialidad from ESPECIALIDAD join especialidades ON especialidad.id_especialidad = especialidades.id_especialidad where rut = 20521;

select numero from NUM_TELEFONOS join TELEFONOS_B ON NUM_TELEFONOS.id_NUMERO = TELEFONOS_B.id_NUMERO where base = 1;

select SERIAL from ARMAMENTO join ARSENAL ON ARMAMENTO.id_ARMAMENTO = ARSENAL.id_ARMAMENTO where ID_EQUIPO = 1;

SELECT * FROM ESPECIALIDADES;

