DELIMITER $
CREATE PROCEDURE INSERTAR_USUARIO(IN RUT_I INT,IN ROL_I INT,IN NOMBRE_ROL_I VARCHAR(100),
IN NOMBRE_USUARIO_I VARCHAR(100),IN PASWORD_I VARCHAR(100))
BEGIN
	INSERT INTO USUARIO (RUT,ROL,NOMBRE_ROL,NOMBRE_USUARIO,PASWORD) VALUES (RUT_I,ROL_I,NOMBRE_ROL_I,NOMBRE_USUARIO_I,PASWORD_I);
END $

DELIMITER $
CREATE PROCEDURE INSERTAR_BOLETA(IN ID_PEDIDO_I INT,IN PRODUCTOS_I VARCHAR(100),
IN RUT_I INT,IN TOTAL_F_I INT)
BEGIN
	INSERT INTO BOLETA (ID_PEDIDO,PRODUCTOS,RUT,TOTAL_F) VALUES (ID_PEDIDO_I,PRODUCTOS_I,RUT_I,TOTAL_F_I);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_DETALLE_PEDIDO(IN ID_PEDIDO_I INT,
IN ID_PRODUCTO_I INT,IN RUT_I INT,IN CANTIDAD_I INT)
BEGIN
	DECLARE CANT_I INT;
    DECLARE PRECIO_I INT;
	SET CANT_I = (SELECT CONTAR_PRO(ID_PEDIDO_I));
    SET PRECIO_I = (SELECT PRECIO FROM PRODUCTO WHERE ID_PRODUCTO = ID_PRODUCTO_I);
    CALL ACTUALIZAR_CANT_PEDIDO(ID_PEDIDO_I, CANT_I);
	INSERT INTO DETALLE_PEDIDO (ID_PEDIDO,ID_PRODUCTO,RUT,CANTIDAD,PRECIO) VALUES (ID_PEDIDO_I,ID_PRODUCTO_I,RUT_I,CANTIDAD_I,PRECIO_I);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_PEDIDO(IN RUT_I INT,
IN PRODUCTOS_I VARCHAR(100),IN CANT_PRO_I INT, IN TOTAL_I INT, IN NRO_MESA_I INT, IN ESTADO_I INT)
BEGIN
	INSERT INTO PEDIDO (RUT,PRODUCTOS,CANT_PRO,TOTAL,NRO_MESA,ESTADO) 
    VALUES (RUT_I,PRODUCTOS_I,CANT_PRO_I,TOTAL_I,NRO_MESA_I,ESTADO_I);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_PRODUCTO(IN NOMBRE_I VARCHAR(100),
IN PRECIO_I INT,IN STOCK_I INT)
BEGIN
	INSERT INTO PRODUCTO (NOMBRE, PRECIO, STOCK) 
    VALUES (NOMBRE_I, PRECIO_I, STOCK_I);
END$

