CREATE OR REPLACE PROCEDURE INSERTAR_ACCESORIOS(
    CODIGO_ACCESORIO_I IN ACCESORIOS.CÓDIGO_ACCESORIO%TYPE,
    NOMBRE_I IN ACCESORIOS.NOMBRE%TYPE,
    INDICACIONES_I IN ACCESORIOS.NOMBRE%TYPE,
    RESULTADO OUT VARCHAR2,
    MENSAJE OUT VARCHAR2
    )
IS
    VERIFICADOR_ACCESORIO NUMBER; 
    ACCESORIO_YA_EXISTE EXCEPTION;   
   
BEGIN
    LOCK TABLE ACCESORIOS IN ROW EXCLUSIVE MODE;
    SELECT COUNT(CÓDIGO_ACCESORIO) INTO VERIFICADOR_ACCESORIO FROM ACCESORIOS WHERE CÓDIGO_ACCESORIO = CODIGO_ACCESORIO_I;
    IF VERIFICADOR_ACCESORIO = 0 THEN
        INSERT INTO ACCESORIOS VALUES(CODIGO_ACCESORIO_I, NOMBRE_I, INDICACIONES_I);
        MENSAJE:= 'ACCESORIO INGRESADO CORRECTAMENTE';
        RESULTADO:= 'TRUE';
        COMMIT;
    ELSE
        RAISE ACCESORIO_YA_EXISTE;
    END IF;
    
    EXCEPTION
        WHEN ACCESORIO_YA_EXISTE THEN
            RESULTADO := 'FALSE' ;
            MENSAJE := 'EL ID DE ACCESORIO YA EXISTE EN LA BASE DE DATOS';
            ROLLBACK;
            
        WHEN OTHERS THEN
            RESULTADO := 'FALSE';
            MENSAJE := 'HA OCURRIDO UN ERROR EN LA BASE DE DATOS -' || SQLERRM || ' - ' || SQLCODE;
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE INSERTAR_DIRECCION(
    ID_DIRECCION_I IN DIRECCION.ID_DIRECCION%TYPE,
    CODIGO_DIRECCION_I IN DIRECCION.CODIGO_DIRECCION%TYPE,
    REGION_I IN DIRECCION.REGION%TYPE,
    CIUDAD_I IN DIRECCION.CIUDAD%TYPE,
    CALLE_I IN DIRECCION.CALLE%TYPE,
    NUMERO_I IN DIRECCION.NUMERO%TYPE,
    CODIGO_POSTAL_I IN DIRECCION.CODIGO_POSTAL%TYPE,
    RESULTADO OUT VARCHAR2,
    MENSAJE OUT VARCHAR2
    )
IS
    VERIFICADOR_DIRECCION NUMBER; 
    DIRECCION_YA_EXISTE EXCEPTION;   
   
BEGIN
    LOCK TABLE DIRECCION IN ROW EXCLUSIVE MODE;
    SELECT COUNT(ID_DIRECCION) INTO VERIFICADOR_DIRECCION FROM DIRECCION WHERE ID_DIRECCION = ID_DIRECCION_I;
    IF VERIFICADOR_DIRECCION = 0 THEN
        INSERT INTO DIRECCION VALUES(ID_DIRECCION_I, CODIGO_DIRECCION_I, REGION_I, CIUDAD_I, CALLE_I, NUMERO_I, CODIGO_POSTAL_I);
        MENSAJE:= 'DIRECCION INGRESADO CORRECTAMENTE';
        RESULTADO:= 'TRUE';
        COMMIT;
    ELSE
        RAISE DIRECCION_YA_EXISTE;
    END IF;
    
    EXCEPTION
        WHEN DIRECCION_YA_EXISTE THEN
            RESULTADO := 'FALSE' ;
            MENSAJE := 'EL ID DE DIRECCION YA EXISTE EN LA BASE DE DATOS';
            ROLLBACK;
            
        WHEN OTHERS THEN
            RESULTADO := 'FALSE';
            MENSAJE := 'HA OCURRIDO UN ERROR EN LA BASE DE DATOS -' || SQLERRM || ' - ' || SQLCODE;
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE INSERTAR_RANGOS(
    ID_RANGO_I IN DIRECCION.ID_RANGO%TYPE,
    CODIGO_DIRECCION_I IN DIRECCION.CODIGO_DIRECCION%TYPE,
    REGION_I IN DIRECCION.REGION%TYPE,
    CIUDAD_I IN DIRECCION.CIUDAD%TYPE,
    CALLE_I IN DIRECCION.CALLE%TYPE,
    NUMERO_I IN DIRECCION.NUMERO%TYPE,
    CODIGO_POSTAL_I IN DIRECCION.CODIGO_POSTAL%TYPE,
    RESULTADO OUT VARCHAR2,
    MENSAJE OUT VARCHAR2
    )
IS
    VERIFICADOR_DIRECCION NUMBER; 
    DIRECCION_YA_EXISTE EXCEPTION;   
   
BEGIN
    LOCK TABLE DIRECCION IN ROW EXCLUSIVE MODE;
    SELECT COUNT(ID_DIRECCION) INTO VERIFICADOR_DIRECCION FROM DIRECCION WHERE ID_DIRECCION = ID_DIRECCION_I;
    IF VERIFICADOR_DIRECCION = 0 THEN
        INSERT INTO DIRECCION VALUES(ID_DIRECCION_I, CODIGO_DIRECCION_I, REGION_I, CIUDAD_I, CALLE_I, NUMERO_I, CODIGO_POSTAL_I);
        MENSAJE:= 'DIRECCION INGRESADO CORRECTAMENTE';
        RESULTADO:= 'TRUE';
        COMMIT;
    ELSE
        RAISE DIRECCION_YA_EXISTE;
    END IF;
    
    EXCEPTION
        WHEN DIRECCION_YA_EXISTE THEN
            RESULTADO := 'FALSE' ;
            MENSAJE := 'EL ID DE DIRECCION YA EXISTE EN LA BASE DE DATOS';
            ROLLBACK;
            
        WHEN OTHERS THEN
            RESULTADO := 'FALSE';
            MENSAJE := 'HA OCURRIDO UN ERROR EN LA BASE DE DATOS -' || SQLERRM || ' - ' || SQLCODE;
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE INSERTAR_ARMAMENTO(
    ID_ARMAMENTO_I IN ARMAMENTO.ID_ARMAMENTO%TYPE,
    SERIAL_I IN ARMAMENTO.SERIAL%TYPE,
    TIPO_I IN ARMAMENTO.TIPO%TYPE,
    PELIGROSIDAD_I IN ARMAMENTO.PELIGROSIDAD%TYPE,
    CALIBRE_I IN ARMAMENTO.CALIBRE%TYPE,
    PESO_I IN ARMAMENTO.PESO%TYPE,
    RESULTADO OUT VARCHAR2,
    MENSAJE OUT VARCHAR2
    )
IS
    VERIFICADOR_ARMAMENTO NUMBER; 
    ARMAMENTO_YA_EXISTE EXCEPTION;   
   
BEGIN
    LOCK TABLE ARMAMENTO IN ROW EXCLUSIVE MODE;
    SELECT COUNT(ID_ARMAMENTO) INTO VERIFICADOR_ARMAMENTO FROM ARMAMENTO WHERE ID_ARMAMENTO = ID_ARMAMENTO_I;
    IF VERIFICADOR_ARMAMENTO = 0 THEN
        INSERT INTO ARMAMENTO VALUES(ID_ARMAMENTO_I, SERIAL_I, TIPO_I, PELIGROSIDAD_I, CALIBRE_I, PESO_I);
        MENSAJE:= 'ARMAMENTO INGRESADO CORRECTAMENTE';
        RESULTADO:= 'TRUE';
        COMMIT;
    ELSE
        RAISE ARMAMENTO_YA_EXISTE;
    END IF;
    
    EXCEPTION
        WHEN ARMAMENTO_YA_EXISTE THEN
            RESULTADO := 'FALSE' ;
            MENSAJE := 'EL ID DE ARMAMENTO YA EXISTE EN LA BASE DE DATOS';
            ROLLBACK;
            
        WHEN OTHERS THEN
            RESULTADO := 'FALSE';
            MENSAJE := 'HA OCURRIDO UN ERROR EN LA BASE DE DATOS -' || SQLERRM || ' - ' || SQLCODE;
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE INSERTAR_BASE(
    CODIGO_BASE_I IN BASES.CODIGO_BASE%TYPE,
    NOMBRE_I IN BASES.NOMBRE%TYPE,
    ID_DIRECCION_I IN BASES.ID_DIRECCION%TYPE,
    RESULTADO OUT VARCHAR2,
    MENSAJE OUT VARCHAR2
    )
IS
    VERIFICADOR_BASE NUMBER; 
    BASE_YA_EXISTE EXCEPTION;   
   
BEGIN
    LOCK TABLE BASES IN ROW EXCLUSIVE MODE;
    SELECT COUNT(CODIGO_BASE) INTO VERIFICADOR_BASE FROM BASES WHERE CODIGO_BASE = CODIGO_BASE_I;
    IF VERIFICADOR_BASE = 0 THEN
        INSERT INTO BASES VALUES(CODIGO_BASE_I, NOMBRE_I, ID_DIRECCION_I);
        MENSAJE:= 'BASE INGRESADO CORRECTAMENTE';
        RESULTADO:= 'TRUE';
        COMMIT;
    ELSE
        RAISE BASE_YA_EXISTE;
    END IF;
    
    EXCEPTION
        WHEN BASE_YA_EXISTE THEN
            RESULTADO := 'FALSE' ;
            MENSAJE := 'EL ID DE BASE YA EXISTE EN LA BASE DE DATOS';
            ROLLBACK;
            
        WHEN OTHERS THEN
            RESULTADO := 'FALSE';
            MENSAJE := 'HA OCURRIDO UN ERROR EN LA BASE DE DATOS -' || SQLERRM || ' - ' || SQLCODE;
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE INSERTAR_ALTO_MANDO(
    ID_ALTO_MANDO_I IN ALTO_MANDO.ID_ALTO_MANDO%TYPE,
    NOMBRE_ALTO_MANDO_I IN ALTO_MANDO.NOMBRE_ALTO_MANDO%TYPE,
    NOMBRE_UNIDAD_I IN ALTO_MANDO.NOMBRE_UNIDAD%TYPE,
    CARGO_I IN ALTO_MANDO.CARGO%TYPE,
    ID_RANGO_I IN ALTO_MANDO.ID_RANGO%TYPE,
    RESULTADO OUT VARCHAR2,
    MENSAJE OUT VARCHAR2
    )
IS
    VERIFICADOR_ALTO NUMBER; 
    ALTO_YA_EXISTE EXCEPTION;   
   
BEGIN
    LOCK TABLE ALTO_MANDO IN ROW EXCLUSIVE MODE;
    SELECT COUNT(ID_ALTO_MANDO) INTO VERIFICADOR_ALTO FROM ALTO_MANDO WHERE ID_ALTO_MANDO = ID_ALTO_MANDO_I;
    IF VERIFICADOR_ALTO = 0 THEN
        INSERT INTO ALTO_MANDO VALUES(ID_ALTO_MANDO_I, NOMBRE_ALTO_MANDO_I, NOMBRE_UNIDAD_I, CARGO_I, ID_RANGO_I);
        MENSAJE:= 'ALTO MANDO INGRESADO CORRECTAMENTE';
        RESULTADO:= 'TRUE';
        COMMIT;
    ELSE
        RAISE ALTO_YA_EXISTE;
    END IF;
    
    EXCEPTION
        WHEN ALTO_YA_EXISTE THEN
            RESULTADO := 'FALSE' ;
            MENSAJE := 'EL ID DE ALTO MANDO YA EXISTE EN LA BASE DE DATOS';
            ROLLBACK;
            
        WHEN OTHERS THEN
            RESULTADO := 'FALSE';
            MENSAJE := 'HA OCURRIDO UN ERROR EN LA BASE DE DATOS -' || SQLERRM || ' - ' || SQLCODE;
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE INSERTAR_ARSENAL(
    ID_ARSENAL_I IN ARSENAL.ID_ARSENAL%TYPE,
    ID_EQUIPO_I IN ARSENAL.ID_EQUIPO%TYPE,
    ID_ARMAMENTO_I IN ARSENAL.ID_ARMAMENTO%TYPE,
    RESULTADO OUT VARCHAR2,
    MENSAJE OUT VARCHAR2
    )
IS
    VERIFICADOR_ARSENAL NUMBER; 
    ARSENAL_YA_EXISTE EXCEPTION;   
   
BEGIN
    LOCK TABLE ARSENAL IN ROW EXCLUSIVE MODE;
    SELECT COUNT(ID_ARSENAL) INTO VERIFICADOR_ARSENAL FROM ARSENAL WHERE ID_ARSENAL = ID_ARSENAL_I;
    IF VERIFICADOR_ARSENAL = 0 THEN
        INSERT INTO ARSENAL VALUES(ID_ARSENAL_I, ID_EQUIPO_I, ID_ARMAMENTO_I);
        MENSAJE:= 'ARSENAL INGRESADO CORRECTAMENTE';
        RESULTADO:= 'TRUE';
        COMMIT;
    ELSE
        RAISE ARSENAL_YA_EXISTE;
    END IF;
    
    EXCEPTION
        WHEN ARSENAL_YA_EXISTE THEN
            RESULTADO := 'FALSE' ;
            MENSAJE := 'EL ID DE ARSENAL YA EXISTE EN LA BASE DE DATOS';
            ROLLBACK;
            
        WHEN OTHERS THEN
            RESULTADO := 'FALSE';
            MENSAJE := 'HA OCURRIDO UN ERROR EN LA BASE DE DATOS -' || SQLERRM || ' - ' || SQLCODE;
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE INSERTAR_EQUIPO(
    ID_EQUIPO_I IN EQUIPO.ID_EQUIPO%TYPE,
    NOMBRE_EQUIPO_I IN EQUIPO.NOMBRE_EQUIPO%TYPE,
    CODIGO_ACCESORIO_I IN EQUIPO.CODIGO_ACCESORIO%TYPE,
    RESULTADO OUT VARCHAR2,
    MENSAJE OUT VARCHAR2
    )
IS
    VERIFICADOR_EQUIPO NUMBER; 
    EQUIPO_YA_EXISTE EXCEPTION;   
   
BEGIN
    LOCK TABLE EQUIPO IN ROW EXCLUSIVE MODE;
    SELECT COUNT(ID_EQUIPO) INTO VERIFICADOR_EQUIPO FROM EQUIPO WHERE ID_EQUIPO = ID_EQUIPO_I;
    IF VERIFICADOR_EQUIPO = 0 THEN
        INSERT INTO EQUIPO VALUES(ID_EQUIPO_I, NOMBRE_EQUIPO_I, CODIGO_ACCESORIO_I);
        MENSAJE:= 'EQUIPO INGRESADO CORRECTAMENTE';
        RESULTADO:= 'TRUE';
        COMMIT;
    ELSE
        RAISE EQUIPO_YA_EXISTE;
    END IF;
    
    EXCEPTION
        WHEN EQUIPO_YA_EXISTE THEN
            RESULTADO := 'FALSE' ;
            MENSAJE := 'EL ID DE EQUIPO YA EXISTE EN LA BASE DE DATOS';
            ROLLBACK;
            
        WHEN OTHERS THEN
            RESULTADO := 'FALSE';
            MENSAJE := 'HA OCURRIDO UN ERROR EN LA BASE DE DATOS -' || SQLERRM || ' - ' || SQLCODE;
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE INSERTAR_ESPECIALIDAD(
    ID_EQUIPO_I IN EQUIPO.ID_EQUIPO%TYPE,
    NOMBRE_EQUIPO_I IN EQUIPO.NOMBRE_EQUIPO%TYPE,
    CODIGO_ACCESORIO_I IN EQUIPO.CODIGO_ACCESORIO%TYPE,
    RESULTADO OUT VARCHAR2,
    MENSAJE OUT VARCHAR2
    )
IS
    VERIFICADOR_EQUIPO NUMBER; 
    EQUIPO_YA_EXISTE EXCEPTION;   
   
BEGIN
    LOCK TABLE EQUIPO IN ROW EXCLUSIVE MODE;
    SELECT COUNT(ID_EQUIPO) INTO VERIFICADOR_EQUIPO FROM EQUIPO WHERE ID_EQUIPO = ID_EQUIPO_I;
    IF VERIFICADOR_EQUIPO = 0 THEN
        INSERT INTO EQUIPO VALUES(ID_EQUIPO_I, NOMBRE_EQUIPO_I, CODIGO_ACCESORIO_I);
        MENSAJE:= 'EQUIPO INGRESADO CORRECTAMENTE';
        RESULTADO:= 'TRUE';
        COMMIT;
    ELSE
        RAISE EQUIPO_YA_EXISTE;
    END IF;
    
    EXCEPTION
        WHEN EQUIPO_YA_EXISTE THEN
            RESULTADO := 'FALSE' ;
            MENSAJE := 'EL ID DE EQUIPO YA EXISTE EN LA BASE DE DATOS';
            ROLLBACK;
            
        WHEN OTHERS THEN
            RESULTADO := 'FALSE';
            MENSAJE := 'HA OCURRIDO UN ERROR EN LA BASE DE DATOS -' || SQLERRM || ' - ' || SQLCODE;
            ROLLBACK;
END;